name: Commit quotidien aléatoire

on:
 # schedule:
  #   - cron: '0 8-22 * * *' # Exécute ce workflow à chaque heure pile entre 8h et 22h UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # Assurez-vous d'utiliser la dernière version
    
    - name: Configurer Git
      run: |
        git config --global user.email "baechle.yohan@gmail.com"
        git config --global user.name "Yohan-Baechle"
    
    - name: Vérifie si un commit doit être fait et exécute les commits
      run: |
        # Détermine si c'est le weekend. Les jours de semaine sont < 6 (Lun=1, Dim=7)
        IS_WEEKEND=$(date +%u)
        # Définit le nombre maximal de commits par jour
        MAX_COMMITS=$((1 + $RANDOM % 5))
        # Détermine le nombre de commits à faire, moins de chances le weekend
        COMMIT_TIMES=$(( $IS_WEEKEND < 6 ? $MAX_COMMITS : ($RANDOM % 2) ))

        # Exécute un nombre de fois aléatoire basé sur COMMIT_TIMES
        for i in $(seq 1 $COMMIT_TIMES)
        do
          # S'assure que le dépôt local est à jour avec le dépôt distant
          git pull origin main --rebase

          # Génère un fichier avec la date et l'heure actuelle comme contenu
          DATE=$(date +"%Y-%m-%d %H:%M:%S")
          echo "Dernier commit le $DATE" > date.txt
          # Crée un commit avec un message incluant la date et l'heure actuelle
          git add .
          git commit -m "Automated update: $(date +'%Y-%m-%d %H:%M:%S')"
          # Push les changements
          git push origin main
          
          # Pause aléatoire entre les commits pour plus de naturalité, ajustez selon besoin
          sleep $(( $RANDOM % 3600 ))
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
